name: grupli
description: Grupli - app para organizar grupos reales, quedadas, asistencia, gastos y torneos.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  supabase_flutter: ^2.8.3
  go_router: ^14.6.2
  table_calendar: ^3.1.3
  image_picker: ^1.1.2
  share_plus: ^10.1.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
