name: grupli
description: Grupli - app premium para organizar grupos privados, eventos, calendario, finanzas y torneos.
publish_to: "none"
version: 0.15.13+1513

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.8.3
  intl: ^0.20.2
  image_picker: ^1.1.2
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.3
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
